version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: receipt_api_dev
    volumes:
      - .:/code
      - receipt_uploads:/app/uploads 
    ports:
      - "8000:8000"
    environment:
      - TESSERACT_PATH=/usr/bin/tesseract
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - BACKEND_CORS_ORIGINS=["http://localhost:5173"]
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - UPLOAD_FOLDER=/app/uploads
    depends_on:
      - rabbitmq
      - redis
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: receipt_worker
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/code
      - receipt_uploads:/app/uploads
    environment:
      - TESSERACT_PATH=/usr/bin/tesseract
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - BACKEND_CORS_ORIGINS=["http://localhost:5173"]
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbitmq
      - redis

  # 3. RABBITMQ (The Queue)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Message port
      - "15672:15672" # GUI Console

  # 4. REDIS (The Result Storage)
  redis:
    image: redis:7-alpine
    container_name: redis-receipt

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile.dev
    container_name: receipt_ui_dev
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000


volumes:
  receipt_uploads: