version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: receipt_api_prod
    ports:
      - "8000:8000"
    environment:
      - TESSERACT_PATH=/usr/bin/tesseract
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile.prod
    container_name: receipt_ui_prod
    ports:
      - "80:80"